/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/ara-mesh/ara/cmd/ara-engine */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 18 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// AraOpen opens (or creates) a node and returns an opaque int64 handle.
// crsqlitePath may be empty on desktop (embedded binary is used); on Android
// pass the full path to libcrsqlite.so from the APK's native library dir.
// migrationsJSON is a JSON array of migration objects (see migrationJSON).
// networkID scopes the node to a logical mesh (empty = default network).
// encryption: non-zero enables X25519 keypairs and AES-256-GCM transport encryption.
// licenseKey: Ed25519-signed key from Ara; empty string = 10-node evaluation limit.
// Returns -1 on error.
//
extern long long AraOpen(char* pathC, char* crsqlitePathC, char* migrationsJSONC, char* networkIDC, int encryptionC, char* licenseKeyC);

// AraClose stops the node's run loop and closes the database.
//
extern void AraClose(long long h);

// AraExec executes a write statement. argsJSON is a JSON array of bind values.
// Returns NULL on success, an error string on failure. Caller must AraFree the result.
//
extern char* AraExec(long long h, char* sqlC, char* argsJSONC);

// AraQuery executes a read query and returns the result as a JSON array of
// objects keyed by column name. Returns {"error":"..."} on failure.
// Caller must AraFree the result.
//
extern char* AraQuery(long long h, char* sqlC, char* argsJSONC);

// AraQueryRow executes a query and returns the first row as a JSON object,
// or null if no rows were returned. Returns {"error":"..."} on failure.
// Caller must AraFree the result.
//
extern char* AraQueryRow(long long h, char* sqlC, char* argsJSONC);

// AraExecTraced is like AraExec but propagates a W3C traceparent so Go spans
// are linked as children of the caller's trace.
//
extern char* AraExecTraced(long long h, char* traceparentC, char* sqlC, char* argsJSONC);

// AraSyncTraced is like AraSync but propagates a W3C traceparent.
//
extern char* AraSyncTraced(long long h, char* traceparentC);

// AraSync triggers an immediate sync broadcast. Returns NULL on success.
// Caller must AraFree any non-NULL result.
//
extern char* AraSync(long long h);

// AraAddTransportMQTT adds an MQTT transport to the node.
// configJSON: {"broker_url":"tcp://...","network_id":"..."}
// Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraAddTransportMQTT(long long h, char* configJSONC);

// AraAddTransportUDP adds a UDP LAN transport. port=0 uses default (7946).
// Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraAddTransportUDP(long long h, int port);

// AraAddTransportUDPSeeds adds a UDP LAN transport with explicit seed peers.
// seeds is a JSON array of "host:port" strings, e.g. `["127.0.0.1:7946"]`.
// port=0 uses default (7946). Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraAddTransportUDPSeeds(long long h, int port, char* seeds);

// AraAddTransportMeshtastic adds a Meshtastic LoRa transport via USB serial.
// portPath is the serial device path, e.g. "/dev/ttyUSB0" or "/dev/ttyACM0".
// channel is the Meshtastic channel index (0-7, default 0).
// Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraAddTransportMeshtastic(long long h, char* portPathC, int channel);

// AraNodeID returns this node's UUID string. Caller must AraFree the result.
//
extern char* AraNodeID(long long h);

// AraSchemaVersion returns the highest applied migration version, or 0.
//
extern int AraSchemaVersion(long long h);

// AraPeers returns a JSON array of peer info objects. Caller must AraFree the result.
//
extern char* AraPeers(long long h);

// AraPeerGraph returns the mesh topology as a JSON object with "nodes" and
// "edges" arrays. Each node has {id, health, self} and each edge has
// {source, target, direct}. Caller must AraFree the result.
//
extern char* AraPeerGraph(long long h);

// AraSetBlobDir configures the blob store directory for the node and sets
// the sync policy. mode: 0=none, 1=thumb_only, 2=full.
// maxBytes and maxBlobSize are 0 for unlimited.
// Returns NULL on success, error string on failure. Caller must AraFree.
//
extern char* AraSetBlobDir(long long h, char* dirC, int mode, long long maxBytes, long long maxBlobSize);

// AraBlobIngest copies a local file into the blob store, records metadata in
// ara_blobs, marks it locally available, and returns its SHA-256 id.
// mimeTypeC is the MIME type of the file (e.g. "image/jpeg"); pass "" to use
// "application/octet-stream".
// Returns the id string on success, or {"error":"..."} on failure.
// Caller must AraFree the result.
//
extern char* AraBlobIngest(long long h, char* pathC, char* mimeTypeC);

// AraBlobPath returns the filesystem path of a stored blob, or "" if not present.
// Caller must AraFree the result.
//
extern char* AraBlobPath(long long h, char* idC);

// AraFree releases a C string previously returned by any Ara function.
// Always call this on non-NULL strings returned by the API.
//
extern void AraFree(char* ptr);

// AraInitOTLP initialises OpenTelemetry exporting to the given gRPC collector.
// addr is "host:port" (e.g. "192.168.1.100:4317"). serviceName defaults to
// "ara-android" if empty. Safe to call after AraOpen on the same handle.
// Returns NULL on success, error string on failure.
//
extern char* AraInitOTLP(long long h, char* addrC, char* serviceNameC);

// AraPublicKey returns the node's X25519 public key as a hex string.
// Returns "" if encryption is not enabled. Caller must AraFree the result.
//
extern char* AraPublicKey(long long h);

// AraAllowPeer adds a peer's public key to the CRDT-synced allowlist.
// pubkeyHex is the hex-encoded X25519 public key from AraPublicKey.
// label is a human-readable name. Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraAllowPeer(long long h, char* pubkeyHexC, char* labelC);

// AraRevokePeer marks a peer's public key as revoked in the CRDT-synced allowlist.
// pubkeyHex is the hex-encoded X25519 public key from AraPublicKey.
// Returns NULL on success, error string on failure.
// Caller must AraFree any non-NULL result.
//
extern char* AraRevokePeer(long long h, char* pubkeyHexC);
extern void AraSetSyncInterval(long long h, int secondsC);

#ifdef __cplusplus
}
#endif
